/* FortiOS 7 Policy & Objects: object databases and CRUD. */
function poRender(k){const d=poDefs[k],b=$(`${k}-body`);if(!b)return;b.innerHTML='';d.collection().forEach(x=>{const tr=document.createElement('tr');if(x.id===poSel[poKey(k)])tr.classList.add('selected');tr.innerHTML=d.row(x).map(v=>`<td>${esc(String(v??''))}</td>`).join('');tr.addEventListener('click',()=>{poSel[poKey(k)]=x.id;poRender(k)});tr.addEventListener('dblclick',()=>{if(!x.builtin)poObjectModal(k,x)});b.append(tr)});poButtons()}
function poRenderIsdb(){const b=$('internet-services-body');if(!b)return;const q=($('isdb-search')?.value||'').toLowerCase();b.innerHTML='';state.internetServices.filter(x=>`${x.id} ${x.name} ${x.category}`.toLowerCase().includes(q)).forEach(x=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${x.id}</td><td>${esc(x.name)}</td><td>${esc(x.category)}</td><td>${esc(x.protocol)}</td><td class="status-enabled">● Enabled</td>`;b.append(tr)})}

function poObjectModal(k,x=null){
  const edit=!!x;if(x?.builtin)return;let html='';
  if(k==='addresses')html=`<div class="form-grid"><div class="field"><label>Name</label><input id="o-name" value="${esc(x?.name||'')}"></div><div class="field"><label>Type</label><select id="o-type"><option>Subnet</option><option>IP Range</option><option>FQDN</option></select></div><div class="field full"><label>Value</label><input id="o-value" value="${esc(x?.value||'192.168.10.0/24')}"></div><div class="field"><label>Interface</label><select id="o-interface"><option>any</option>${state.interfaces.map(i=>`<option>${esc(i.name)}</option>`).join('')}</select></div></div>`;
  if(k==='services')html=`<div class="form-grid"><div class="field"><label>Name</label><input id="o-name" value="${esc(x?.name||'')}"></div><div class="field"><label>Protocol</label><select id="o-protocol"><option>TCP</option><option>UDP</option><option>TCP/UDP</option><option>ICMP</option></select></div><div class="field"><label>Destination Port</label><input id="o-port" value="${esc(x?.port||'8080')}"></div></div>`;
  if(k==='schedules')html=`<div class="form-grid"><div class="field"><label>Name</label><input id="o-name" value="${esc(x?.name||'')}"></div><div class="field"><label>Type</label><select id="o-type"><option>Recurring</option><option>One-time</option></select></div><div class="field full"><label>Days (Sun,Mon,...)</label><input id="o-days" value="${esc((x?.days||['Sun','Mon','Tue','Wed','Thu']).join(','))}"></div><div class="field"><label>Start</label><input id="o-start" type="time" value="${esc(x?.start||'08:00')}"></div><div class="field"><label>End</label><input id="o-end" type="time" value="${esc(x?.end||'18:00')}"></div><div class="field"><label>Start Date</label><input id="o-start-date" type="date" value="${esc(x?.startDate||'')}"></div><div class="field"><label>End Date</label><input id="o-end-date" type="date" value="${esc(x?.endDate||'')}"></div></div>`;
  if(k==='vips')html=`<div class="form-grid"><div class="field"><label>Name</label><input id="o-name" value="${esc(x?.name||'')}"></div><div class="field"><label>Interface</label><select id="o-interface">${state.interfaces.map(i=>`<option>${esc(i.name)}</option>`).join('')}</select></div><div class="field"><label>External IP</label><input id="o-ext" value="${esc(x?.externalIp||'192.168.80.49')}"></div><div class="field"><label>Mapped IP</label><input id="o-map" value="${esc(x?.mappedIp||'192.168.1.100')}"></div><div class="field"><label>Port Forwarding</label><input id="o-pf" type="checkbox" ${x?.portForward?'checked':''}></div><div class="field"><label>Protocol</label><select id="o-protocol"><option>TCP</option><option>UDP</option></select></div><div class="field"><label>External Port</label><input id="o-eport" type="number" value="${x?.externalPort||443}"></div><div class="field"><label>Mapped Port</label><input id="o-mport" type="number" value="${x?.mappedPort||443}"></div></div>`;
  if(k==='ip-pools')html=`<div class="form-grid"><div class="field"><label>Name</label><input id="o-name" value="${esc(x?.name||'')}"></div><div class="field"><label>Type</label><select id="o-type"><option>Overload</option><option>One-to-One</option></select></div><div class="field"><label>Start IP</label><input id="o-start-ip" value="${esc(x?.startIp||'192.168.80.100')}"></div><div class="field"><label>End IP</label><input id="o-end-ip" value="${esc(x?.endIp||'192.168.80.110')}"></div></div>`;
  if(k==='protocol-options')html=`<div class="form-grid"><div class="field"><label>Name</label><input id="o-name" value="${esc(x?.name||'')}"></div><div class="field"><label>TCP Half Close</label><input id="o-half" type="number" value="${x?.tcpHalfClose||120}"></div><div class="field"><label>TCP Time Wait</label><input id="o-wait" type="number" value="${x?.tcpTimeWait||1}"></div></div>`;
  if(k==='traffic-shaping')html=`<div class="form-grid"><div class="field"><label>Name</label><input id="o-name" value="${esc(x?.name||'')}"></div><div class="field"><label>Type</label><select id="o-type"><option>Shared</option><option>Per-IP</option></select></div><div class="field"><label>Maximum kbps</label><input id="o-max" type="number" value="${x?.maximumBandwidth||10000}"></div><div class="field"><label>Guaranteed kbps</label><input id="o-guaranteed" type="number" value="${x?.guaranteedBandwidth||0}"></div><div class="field"><label>Priority</label><select id="o-priority"><option>High</option><option>Medium</option><option>Low</option></select></div></div>`;
  openModal(`${edit?'Edit':'Create'} ${poDefs[k].title.replace(/s$/,'')}`,html,[{label:'Cancel',className:'btn-secondary',action:closeModal},{label:edit?'OK':'Create',className:'btn-primary',action:()=>poSaveObject(k,x?.id)}]);
  if(x)['o-type','o-interface','o-protocol','o-priority'].forEach(id=>{if($(id)){const key=id==='o-interface'?'interface':id==='o-protocol'?'protocol':id==='o-priority'?'priority':'type';$(id).value=x[key]||$(id).value}})
}

function poSaveObject(k,id){const c=poDefs[k].collection(),name=$('o-name').value.trim();if(!/^[A-Za-z0-9_.-]{1,63}$/.test(name)||c.some(x=>x.name.toLowerCase()===name.toLowerCase()&&x.id!==id)){alert('Name must be unique.');return}let o={id:id||uid(),name};if(k==='addresses'){o.type=$('o-type').value;o.value=$('o-value').value.trim();o.interface=$('o-interface').value;if(o.type==='Subnet'&&!isCIDR(o.value)){alert('Use CIDR such as 192.168.10.0/24.');return}if(o.type==='IP Range'){const r=o.value.split('-');if(r.length!==2||!isIPv4(r[0].trim())||!isIPv4(r[1].trim())||ipToInt(r[0].trim())>ipToInt(r[1].trim())){alert('Use start-end IP range.');return}}}if(k==='services'){o.protocol=$('o-protocol').value;o.port=$('o-port').value.trim();if(o.protocol!=='ICMP'&&!/^\d+(-\d+)?$/.test(o.port)){alert('Enter a port or port range.');return}}if(k==='schedules'){o.type=$('o-type').value;o.days=$('o-days').value.split(',').map(v=>v.trim()).filter(Boolean);o.start=$('o-start').value;o.end=$('o-end').value;o.startDate=$('o-start-date').value;o.endDate=$('o-end-date').value}if(k==='vips'){o.interface=$('o-interface').value;o.externalIp=$('o-ext').value.trim();o.mappedIp=$('o-map').value.trim();o.portForward=$('o-pf').checked;o.protocol=$('o-protocol').value;o.externalPort=+$('o-eport').value;o.mappedPort=+$('o-mport').value;if(!isIPv4(o.externalIp)||!isIPv4(o.mappedIp)){alert('Enter valid IPv4 addresses.');return}}if(k==='ip-pools'){o.type=$('o-type').value;o.startIp=$('o-start-ip').value.trim();o.endIp=$('o-end-ip').value.trim();if(!isIPv4(o.startIp)||!isIPv4(o.endIp)||ipToInt(o.startIp)>ipToInt(o.endIp)){alert('Enter a valid IP range.');return}}if(k==='protocol-options'){o.tcpHalfClose=+$('o-half').value;o.tcpTimeWait=+$('o-wait').value}if(k==='traffic-shaping'){o.type=$('o-type').value;o.maximumBandwidth=+$('o-max').value;o.guaranteedBandwidth=+$('o-guaranteed').value;o.priority=$('o-priority').value;if(o.maximumBandwidth<1||o.guaranteedBandwidth<0||o.guaranteedBandwidth>o.maximumBandwidth){alert('Invalid bandwidth values.');return}}const i=c.findIndex(x=>x.id===id);if(i>=0)c[i]=o;else c.push(o);saveState();closeModal();poRender(k)}
function poDelete(k){const x=poSelected(k);if(!x||x.builtin)return;const kind=k==='addresses'?'address':k==='services'?'service':k==='schedules'?'schedule':k==='vips'?'vip':k==='ip-pools'?'ipPool':k==='protocol-options'?'protocolOptions':'trafficShaper',refs=poRefs(kind,x.name);if(refs){alert(`${x.name} is referenced by ${refs} firewall policy item(s).`);return}if(confirm(`Delete "${x.name}"?`)){const c=poDefs[k].collection(),i=c.findIndex(v=>v.id===x.id);c.splice(i,1);poSel[poKey(k)]=null;saveState();poRender(k)}}
function poRefs(kind,name){return state.policies.filter(p=>kind==='address'?(p.source===name||p.destination===name):kind==='service'?p.service===name:kind==='schedule'?(p.schedule||'always')===name:kind==='vip'?p.destination===name:kind==='ipPool'?(p.nat&&p.ipPool===name):kind==='protocolOptions'?(p.protocolOptions||'default')===name:p.trafficShaper===name).length}
