/* FortiOS 7 Policy & Objects: matching engine and final render integration. */
function poAddr(name,ip){if(name==='all')return true;const a=state.addresses.find(x=>x.name===name);if(!a)return false;if(a.type==='Subnet')return cidrContains(a.value,ip);if(a.type==='IP Range'){const r=a.value.split('-').map(v=>v.trim());return isIPv4(r[0])&&isIPv4(r[1])&&ipToInt(ip)>=ipToInt(r[0])&&ipToInt(ip)<=ipToInt(r[1])}return false}
function poSchedule(name,now=new Date()){if(!name||name==='always')return true;const s=state.schedules.find(x=>x.name===name);if(!s)return false;if(s.type==='One-time'){const d=now.toISOString().slice(0,10);return !!s.startDate&&!!s.endDate&&d>=s.startDate&&d<=s.endDate}const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];if(!(s.days||[]).includes(days[now.getDay()]))return false;const m=now.getHours()*60+now.getMinutes(),a=(s.start||'00:00').split(':').map(Number),b=(s.end||'23:59').split(':').map(Number),st=a[0]*60+a[1],en=b[0]*60+b[1];return st<=en?(m>=st&&m<=en):(m>=st||m<=en)}
function poVip(ip,incoming){return state.vips.find(v=>v.externalIp===ip&&(v.interface===incoming||v.interface==='any'))||null}
function poPrivate(ip){const n=ip.split('.').map(Number);return n[0]===10||(n[0]===172&&n[1]>=16&&n[1]<=31)||(n[0]===192&&n[1]===168)}

function evaluateTraffic({source,destination,incoming,outgoing,service}){const i=findByName(incoming);if(!i||!isInterfaceOperational(i))return{action:'DENY',policyId:'-',reason:`Incoming interface ${incoming} is down`};if(i.addressingMode==='One-Arm Sniffer')return{action:'DENY',policyId:'-',reason:`Interface ${incoming} is in One-Arm Sniffer mode`};const vip=poVip(destination,incoming),dst=vip?.mappedIp||destination,r=findBestRoute(dst);if(!r)return{action:'DENY',policyId:'-',reason:'No route to destination'};if(outgoing&&outgoing!==r.interface)return{action:'DENY',policyId:'-',reason:`Route lookup selects ${r.interface}, not ${outgoing}`};const p=state.policies.find(x=>x.enabled!==false&&(x.from===incoming||x.from==='all')&&(x.to===r.interface||x.to==='all')&&poAddr(x.source,source)&&((vip&&x.destination===vip.name)||poAddr(x.destination,dst))&&(x.service==='ALL'||x.service===service)&&poSchedule(x.schedule));if(!p)return{action:'DENY',policyId:'-',reason:'Implicit deny: no matching firewall policy'};if(p.action==='DENY')return{action:'DENY',policyId:p.id,reason:`Denied by policy ${p.name}`};if(r.interface==='wan'&&poPrivate(source)&&!poPrivate(dst)&&!p.nat)return{action:'DENY',policyId:p.id,reason:`Policy ${p.name} matched but source NAT is disabled for Internet traffic`};if(p.nat&&p.natMode==='Use Dynamic IP Pool'&&!state.ipPools.some(x=>x.name===p.ipPool))return{action:'DENY',policyId:p.id,reason:`Policy ${p.name} references a missing IP Pool`};const why=[`Policy ${p.name} matched`,`route ${r.destination} via ${r.interface}`];if(vip)why.push(`VIP ${vip.name}: ${destination} → ${dst}`);if(p.nat)why.push(p.natMode==='Use Dynamic IP Pool'?`SNAT pool ${p.ipPool}`:'source NAT applied');return{action:'ACCEPT',policyId:p.id,reason:why.join('; '),outgoing:r.interface}}
function poRenderAllObjects(){Object.keys(poDefs).forEach(poRender);poRenderIsdb()}
function renderAll(){renderInterfaces();renderDns();renderRoutes();renderPolicies();renderLogs();renderDashboard();poRenderAllObjects()}
